Rails:
  Enabled: true

AllCops:
  DisplayCopNames: true
  Exclude:
    - db/schema.rb
  TargetRubyVersion: 2.4

Layout/AlignParameters:
  EnforcedStyle: with_fixed_indentation

Lint/BlockAlignment:
  EnforcedStyleAlignWith: start_of_line

Lint/EndAlignment:
  EnforcedStyleAlignWith: variable

Layout/IndentHash:
  EnforcedStyle: consistent

Layout/IndentationWidth:
  Width: 2

Layout/MultilineMethodCallBraceLayout:
  EnforcedStyle: new_line

Style/PercentLiteralDelimiters:
  PreferredDelimiters:
    '%':  '{}'
    '%i': '[]'
    '%q': '{}'
    '%Q': '{}'
    '%r': '{}'
    '%s': '{}'
    '%w': '[]'
    '%W': '[]'
    '%x': '{}'

Style/BlockDelimiters:
  EnforcedStyle: braces_for_chaining

Style/Documentation:
  Enabled: false

Style/EmptyMethod:
  EnforcedStyle: expanded

Style/SymbolArray:
  Enabled: false

Metrics/BlockLength:
  CountComments: false
  Max: 25
  Exclude:
    - app/admin/*.rb
  ExcludedMethods:
    - context
    - describe
    - it
    - shared_examples

Metrics/LineLength:
  Max: 120
