Rails:
  Enabled: true

AllCops:
  DisplayCopNames: true
  TargetRubyVersion: 2.4

Layout/AlignParameters:
  EnforcedStyle: with_fixed_indentation

Lint/BlockAlignment:
  EnforcedStyleAlignWith: start_of_line

Lint/EndAlignment:
  EnforcedStyleAlignWith: variable

Layout/IndentHash:
  EnforcedStyle: consistent

Style/IndentationWidth:
  Width: 2

Style/PercentLiteralDelimiters:
  PreferredDelimiters:
    '%':  '{}'
    '%i': '{}'
    '%q': '{}'
    '%Q': '{}'
    '%r': '{}'
    '%s': '{}'
    '%w': '{}'
    '%W': '{}'
    '%x': '{}'

Style/BlockDelimiters:
  EnforcedStyle: braces_for_chaining

Style/Documentation:
  Enabled: false

Style/MultilineMethodCallBraceLayout:
  EnforcedStyle: new_line

Metrics/BlockLength:
  CountComments: false
  Max: 25
  Exclude:
    - app/admin/*.rb
  ExcludeMethods:
    - context
    - describe
    - it
    - shared_examples

Metrics/LineLength:
  Max: 100
